Added more scammer usernames from my channel
ThioJoe/YT-Spam-Lists pull request #85
Opened 2022-02-08 06:24 UTC by GeoSn0w

My channel is iOS related so these are iCloud Unlock / jailbreak scammers who advertise WhatsApp or Instagram account of theirs.

2022-02-08 12:37 UTC, Firecul requested changes
The names should be `clihacktools` and `aimtoolz` iirc

2022-02-08 12:39 UTC, Firecul commented
Not sure if ThioJoe will ask for links to see the comments or not for the others. I'll leave that to him to decide.

2022-02-08 12:42 UTC, KendallDoesCoding requested changes
Please close this PR and make a issue thread reporting these SpamAccounts with the direct comment url, screenshots if possible. @ThioJoe Doesn't accept PR's, he prefers Issue threads and then he can review accordingly. Thanks!

2022-02-12 16:56 UTC, closed without merging

2022-02-12 17:08 UTC, KendallDoesCoding commented
Thanks